# Generated by Django 3.1.7 on 2021-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
